version: '3'
services:
    php-apache:
        image: chialab/php:7.0-apache
        restart: always
        volumes:
            - "./public_html:/var/www/html"
        ports:
            - "8080:80"
    myadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        ports:
            - "8081:80"
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=${MYSQL_HOST}
        restart: always
        depends_on:
            - mysqldb
    mysqldb:
        image: mysql:5
        container_name: ${MYSQL_HOST}
        restart: always
        env_file:
            - ".env"
        ports:
            - "3306:3306"
